"""
BitcoinScore V3 Clean Scoring Engine.

Pipeline (single pass, no V1/V2 dependency):
  1. normalize  — causal point-in-time normalization via normalizer.py
  2. phase      — continuous (w_bot, w_neutral, w_top) from bottom_confluence.py
  3. wave       — WR computed directly from wave_resonance.py (not via V2)
  4. utilities  — dynamic metric weights via utility_evaluator.py
  5. score      — flat utility-weighted avg + TiZ blend + coherence dampening
  6. signal     — orchestrate() for conviction, flags, divergence

Calibration constants live in data/v3_calibration.json (generated by
tools/calibrate_v3.py). No inline magic numbers.
"""

import datetime
import json
import os

from scraper.normalizer import normalize_metric
from scraper.utility_evaluator import evaluate_all_utilities_continuous
from scraper.bottom_confluence import (
    compute_bottom_confluence,
    load_calibration as _load_bc_cal,
    BOTTOM_PHASE_THRESHOLD,
)
from scraper.tiz import compute_tiz_causal, adaptive_calibration as _tiz_cal
from scraper.wave_resonance import compute_wave_resonance
from scraper.scoring import _oc_coherence

# ── Metric groups (for informational sub-scores only) ─────────────────────────
OC_GROUP   = {'nupl', 'mvrv_z_score', 'rhodl_ratio', 'cvdd_ratio', 'asopr', 'puell', 'lth_supply'}
TECH_GROUP = {'cipherb', 'mayer_multiple', 'fear_greed', 'etf_flows',
              'yield_curve_spread', 'm2_yoy', 'pi_gap', 'funding_rate'}

_CAL_PATH  = 'data/v3_calibration.json'
_cal_cache: dict | None = None


def load_calibration() -> dict:
    """Load scoring constants from data/v3_calibration.json."""
    global _cal_cache
    if _cal_cache is not None:
        return _cal_cache
    if os.path.exists(_CAL_PATH):
        try:
            with open(_CAL_PATH, encoding='utf-8') as f:
                _cal_cache = json.load(f)
                return _cal_cache
        except Exception:
            pass
    raise RuntimeError(
        f'{_CAL_PATH} missing. Run tools/calibrate_v3.py to generate it.'
    )


# ── Normalization ─────────────────────────────────────────────────────────────

_KEY_MAP = {
    'nupl':          'nupl',
    'mvrv':          'mvrv_z_score',
    'rhodl_ratio':   'rhodl_ratio',
    'cvdd_ratio':    'cvdd_ratio',
    'asopr':         'asopr',
    'puell_multiple':'puell',
    'mayer_multiple':'mayer_multiple',
    'fear_greed':    'fear_greed',
    'm2_mom':        'm2_yoy',
    'yield_curve':   'yield_curve_spread',
    'etf_flows':     'etf_flows',
    'funding_rate':  'funding_rate',
    'dxy':           'dxy',
    'lth_supply_pct':'lth_supply',
}


def _extract_pi_gap(v):
    if v is None:
        return None
    while isinstance(v, dict):
        if 'gap_pct' in v:
            return v['gap_pct']
        v = v.get('value')
    return float(v) if isinstance(v, (int, float)) else None


def _map_pi_gap(v) -> int | None:
    gap = _extract_pi_gap(v)
    if gap is None:
        return None
    gap = max(0.0, min(70.0, float(gap)))
    return round(((70.0 - gap) / 70.0) * 100)


def _extract_cipherb(cb) -> tuple[int | None, int | None, int | None]:
    """Return (weekly_raw, daily_raw, blended_score) from cipherb metric."""
    if not isinstance(cb, dict):
        return None, None, None
    val_dict = cb.get('value', cb)
    if not isinstance(val_dict, dict):
        return None, None, None
    w = val_dict.get('weekly_score')
    d = val_dict.get('daily_score')
    weekly_raw = round(w) if w is not None else None
    daily_raw  = round(d) if d is not None else None
    if w is None:
        return weekly_raw, daily_raw, None
    if val_dict.get('fast_bearish_div'):
        w = min(100.0, w + 12)
    elif val_dict.get('fast_bullish_div'):
        w = max(0.0, w - 12)
    if d is not None:
        if val_dict.get('daily_fast_bearish_div'):
            d = min(100.0, d + 12)
        elif val_dict.get('daily_fast_bullish_div'):
            d = max(0.0, d - 12)
        blended = round(0.8 * w + 0.2 * d)
    else:
        blended = round(w)
    return weekly_raw, daily_raw, blended


def _normalize(raw_metrics: dict, target_date: datetime.date) -> dict:
    """Normalize all raw metrics to [0, 100] risk scores."""
    normalized: dict[str, int | None] = {}
    for raw_k, norm_k in _KEY_MAP.items():
        val = raw_metrics.get(raw_k)
        normalized[norm_k] = normalize_metric(norm_k, val, target_date)

    # Pi Cycle Gap
    pi_raw = (raw_metrics.get('pi_cycle')
              or raw_metrics.get('pi_cycle_gap_pct')
              or raw_metrics.get('pi_gap'))
    normalized['pi_gap'] = _map_pi_gap(pi_raw)

    # CipherB (weekly + daily blend, divergence-adjusted)
    cb = raw_metrics.get('cipherb')
    weekly_raw, daily_raw, blended = _extract_cipherb(cb)
    normalized['cipherb']         = blended
    normalized['cipherb_weekly']  = weekly_raw
    normalized['cipherb_daily']   = daily_raw

    return normalized


# ── Phase weights ─────────────────────────────────────────────────────────────

def _phase_weights(normalized: dict, prev_scores: dict | None) -> tuple[float, float, float, str, int, int]:
    """
    Compute continuous phase weights (w_bot, w_neutral, w_top) summing to 1.

    w_bot: bottom_confluence.py — calibrated from CONFIRMED_BOTTOM_DATES.
    w_top: HMM model proba[2] — proper probability, trained on confirmed cycle data.
           Falls back to 0.0 when model unavailable (safe: neutral wins).

    Returns (w_bot, w_neutral, w_top, phase_label, top_signal, bot_signal).
    """
    w_top, w_bot, w_neutral = 0.0, 0.0, 1.0
    top_signal, bot_signal  = 0, 0
    phase = 'NEUTRAL'

    # ── w_bot: data-driven bottom confluence ──────────────────────────────────
    try:
        confluence = compute_bottom_confluence(normalized, _load_bc_cal())
        if confluence is not None:
            w_bot      = confluence / 100.0
            bot_signal = confluence
    except Exception:
        pass

    # ── w_top: HMM probability (proper probability, sums to 1 with bot/neutral)
    try:
        import os, pickle
        model_path = 'data/v3_phase_model.pkl'
        if os.path.exists(model_path):
            try:
                from tools.train_v3_hmm_model import HMMPhaseClassifier as _hmm_cls
            except ImportError:
                _hmm_cls = None

            class _Unpickler(pickle.Unpickler):
                def find_class(self, module, name):
                    if name == 'HMMPhaseClassifier' and _hmm_cls is not None:
                        return _hmm_cls
                    return super().find_class(module, name)

            with open(model_path, 'rb') as f:
                model_data = _Unpickler(f).load()
            pipeline = model_data['pipeline']

            METRIC_ORDER = [
                'nupl', 'mvrv_z_score', 'rhodl_ratio', 'cvdd_ratio', 'mayer_multiple',
                'asopr', 'etf_flows', 'cipherb_weekly', 'cipherb_daily', 'fear_greed', 'm2_yoy',
            ]
            import numpy as np
            vec = []
            for m in METRIC_ORDER:
                vec.append(normalized.get(m))
            for m in METRIC_ORDER:
                s_now  = normalized.get(m)
                s_prev = (prev_scores or {}).get(m)
                vec.append(s_now - s_prev if (s_now is not None and s_prev is not None) else None)
            row   = [v if v is not None else float('nan') for v in vec]
            probs = pipeline.predict_proba(np.array([row], dtype=float))[0]
            w_top      = float(probs[2])  # only use top probability from HMM
            top_signal = round(w_top * 100)
    except Exception:
        pass

    # ── Consensus fallback when HMM unavailable (w_top still 0.0) ────────────
    # Uses the three best top/bottom discriminating metrics (disc power from
    # confirmed cycle extremes: cipherb +80.9, nupl +45.8, mvrv +44.6).
    # Phase score ≥62 → TOP; continuous w_top scaled 0.65→1.0 above threshold.
    if w_top == 0.0:
        _cb = normalized.get('cipherb')
        _nu = normalized.get('nupl')
        _mv = normalized.get('mvrv_z_score')
        _vals = [v for v in [_cb, _nu, _mv] if v is not None]
        if _vals:
            _ps = sum(_vals) / len(_vals)
            if _ps >= 62:
                w_top      = min(1.0, 0.65 + (_ps - 62) / 38.0 * 0.35)
                top_signal = round(w_top * 100)

    # ── Normalise so w_bot + w_top + w_neutral = 1 ───────────────────────────
    total = w_bot + w_top
    if total > 1.0:
        w_bot  /= total
        w_top  /= total
        w_neutral = 0.0
    else:
        w_neutral = max(0.0, 1.0 - total)

    # Phase label (informational only — no scoring logic gates on this string)
    if w_top > 0.40 and w_top > w_bot:
        phase = 'TOP'
    elif w_bot >= BOTTOM_PHASE_THRESHOLD and w_bot > w_top:
        phase = 'BOTTOM'

    return w_bot, w_neutral, w_top, phase, top_signal, bot_signal


# ── Weighted average helper ───────────────────────────────────────────────────

def _wavg(group_keys: set, normalized: dict, utilities: dict) -> int | None:
    total_uw = total_us = 0.0
    for k in group_keys:
        s = normalized.get(k)
        u = utilities.get(k, 0.5)
        if s is not None:
            total_us += s * u
            total_uw += u
    return round(total_us / total_uw) if total_uw > 0 else None


# ── Main scoring function ─────────────────────────────────────────────────────

def compute_score(
    raw_metrics: dict,
    target_date: datetime.date | str | None = None,
    prev_scores: dict | None = None,
    scores_history: list | None = None,
    btc_price: float | None = None,
) -> dict:
    """
    Compute the composite risk score for a given set of raw metric values.

    Parameters
    ----------
    raw_metrics    : dict  — raw values from live scraper or backtest reconstruction.
    target_date    : date  — used for causal normalization; defaults to today.
    prev_scores    : dict  — metric scores from N days ago (for top signal via Mahalanobis).
    scores_history : list  — [(date_str, score, phase?, w_bot?), ...] for TiZ.
    btc_price      : float — BTC price at target_date (passed through to signal).

    Returns
    -------
    dict with: final_score, phase, w_bot/w_neutral/w_top, tiz_*, oc_coherence,
               coh_factor, utilities, normalized_scores, wave_resonance, onchain_avg,
               tech_avg, top_signal, bot_signal, pi_cross, dxy_adj.
    """
    if isinstance(target_date, str):
        target_date = datetime.date.fromisoformat(target_date)
    elif target_date is None:
        target_date = datetime.date.today()

    cal = load_calibration()
    cd  = cal['coherence_dampening']
    tiz_cfg = cal['tiz']
    dxy_cfg = cal['dxy_modifier']

    # ── 1. Normalize ──────────────────────────────────────────────────────────
    normalized = _normalize(raw_metrics, target_date)

    # ── 2. Phase weights ──────────────────────────────────────────────────────
    if prev_scores is None:
        try:
            from scraper.scoring_v2 import _METRIC_LOOKBACK
            from scraper.wave_history import build_prev_scores_for_wave
            prev_scores = build_prev_scores_for_wave(target_date, _METRIC_LOOKBACK)
        except Exception:
            pass

    w_bot, w_neutral, w_top, phase, top_signal, bot_signal = _phase_weights(normalized, prev_scores)

    # ── 3. Wave Resonance (independent — no V2 required) ─────────────────────
    pi_raw = (raw_metrics.get('pi_cycle')
              or raw_metrics.get('pi_cycle_gap_pct')
              or raw_metrics.get('pi_gap'))
    pi_gap_pct = _extract_pi_gap(pi_raw)

    def _scalar(v):
        """Extract numeric value from either a raw number or a {value: ...} dict."""
        if isinstance(v, dict):
            v = v.get('value')
        return float(v) if isinstance(v, (int, float)) else None

    nupl_raw = _scalar(raw_metrics.get('nupl'))
    wr_overrides = {
        'nupl':           nupl_raw,  # scores.json stores nupl in % — same units as window
        'mvrv':           _scalar(raw_metrics.get('mvrv')),
        'puell':          _scalar(raw_metrics.get('puell_multiple')),
        'cvdd_ratio':     _scalar(raw_metrics.get('cvdd_ratio')),
        'mayer_multiple': _scalar(raw_metrics.get('mayer_multiple')),
        'pi_gap_pct':     pi_gap_pct,
    }
    wr_overrides = {k: v for k, v in wr_overrides.items() if v is not None}
    wr = compute_wave_resonance(
        date=target_date.isoformat(),
        raw_overrides=wr_overrides if wr_overrides else None,
    )

    # ── 4. TiZ — continuous, no phase gate ───────────────────────────────────
    if scores_history is None:
        scores_path = 'data/history/scores.json'
        if os.path.exists(scores_path):
            try:
                with open(scores_path, encoding='utf-8') as f:
                    history_data = json.load(f)
                scores_history = [
                    (r['date'], r.get('final_score'), r.get('phase'), r.get('w_bot'))
                    for r in history_data if r.get('date')
                ]
            except Exception:
                pass

    tiz_score, tiz_days, tiz_calibration = compute_tiz_causal(
        scores_history, target_date
    )
    tiz_maturity = round(tiz_days / tiz_calibration, 3) if tiz_days > 0 else None

    # ── 5. Utility weights ────────────────────────────────────────────────────
    utilities = evaluate_all_utilities_continuous(
        normalized, w_top, w_bot, w_neutral, tiz_maturity
    )

    # ── 6a. Flat utility-weighted average (all metrics) ───────────────────────
    flat_avg = _wavg(OC_GROUP | TECH_GROUP, normalized, utilities)
    oc_avg   = _wavg(OC_GROUP,   normalized, utilities)
    tech_avg = _wavg(TECH_GROUP, normalized, utilities)

    # ── 6b. TiZ blend — continuous, scales with w_bot ─────────────────────────
    final = flat_avg
    if final is not None and tiz_score is not None:
        tw    = tiz_cfg['weight']
        final = round((1.0 - tw * w_bot) * flat_avg + tw * w_bot * tiz_score)

    # ── 6c. DXY macro modifier ────────────────────────────────────────────────
    dxy_score = normalized.get('dxy')
    dxy_adj   = 0.0
    if final is not None and dxy_score is not None:
        if dxy_score > dxy_cfg['high']:
            dxy_adj = -min(dxy_cfg['max_adj'], (dxy_score - dxy_cfg['high']) * dxy_cfg['scale'])
        elif dxy_score < dxy_cfg['low']:
            dxy_adj = min(dxy_cfg['max_adj'], (dxy_cfg['low'] - dxy_score) * dxy_cfg['scale'])
        if dxy_adj != 0.0:
            final = max(0, min(100, round(final + dxy_adj)))

    # ── 6d. Coherence dampening — fully continuous ────────────────────────────
    oc_coherence = _oc_coherence(normalized)
    coh_factor   = 1.0
    if final is not None:
        coh_floor = (
            cd['bottom_coh_floor'] * w_bot
            + cd['neutral_coh_floor'] * w_neutral
            + cd['top_coh_floor']    * w_top
        )
        neutral_target = (
            cd['bottom_neutral_target'] * w_bot
            + cd['neutral_neutral_target'] * w_neutral
            + cd['top_neutral_target']    * w_top
        )
        coh_factor = round(coh_floor + (1.0 - coh_floor) * oc_coherence, 3)
        final = round(neutral_target + (final - neutral_target) * coh_factor)

    # ── 6e. Pi Cycle top override ─────────────────────────────────────────────
    # pi_raw is a dict with 'cross' key during live scoring, but a plain float
    # (pi_gap_pct) during recompute from scores.json — detect both forms.
    _pi_gap_val = _extract_pi_gap(pi_raw)
    pi_cross = (
        (isinstance(pi_raw, dict) and bool(pi_raw.get('cross')))
        or (_pi_gap_val is not None and _pi_gap_val <= 0)
    )
    if pi_cross and final is not None:
        final = max(final, 85)

    return {
        'final_score':        final,
        'phase':              phase,
        'w_bot':              round(w_bot, 3),
        'w_neutral':          round(w_neutral, 3),
        'w_top':              round(w_top, 3),
        'top_signal':         top_signal,
        'bot_signal':         bot_signal,
        'onchain_avg':        oc_avg,
        'tech_avg':           tech_avg,
        'tiz_score':          tiz_score,
        'tiz_days':           tiz_days,
        'tiz_maturity':       tiz_maturity,
        'tiz_calibration':    tiz_calibration,
        'oc_coherence':       round(oc_coherence, 3),
        'coh_factor':         coh_factor,
        'pi_cross':           pi_cross,
        'dxy_adj':            round(dxy_adj, 2),
        'wave_resonance':     wr,
        'utilities':          utilities,
        'normalized_scores':  {
            k: round(v) for k, v in normalized.items()
            if v is not None and k not in ('cipherb_weekly', 'cipherb_daily')
        },
    }
