"""
BitcoinScore V3 Clean Scoring Engine.

Pipeline (single pass, no V1/V2 dependency):
  1. normalize  — causal point-in-time normalization via normalizer.py
  2. phase      — continuous (w_bot, w_neutral, w_top) from bottom_confluence.py
  3. wave       — WR computed directly from wave_resonance.py (not via V2)
  4. utilities  — dynamic metric weights via utility_evaluator.py
  5. score      — flat utility-weighted avg + TiZ blend + coherence dampening
  6. signal     — orchestrate() for conviction, flags, divergence

Calibration constants live in data/v3_calibration.json (generated by
tools/calibrate_v3.py). No inline magic numbers.
"""

import datetime
import json
import math
import os

from scraper.normalizer import normalize_metric
from scraper.cycle_normalizer import price_cycle_percentile
from scraper.utility_evaluator import evaluate_all_utilities_continuous, blend_phase_with_cycle_prior
from scraper.bottom_confluence import (
    compute_bottom_confluence,
    load_calibration as _load_bc_cal,
    BOTTOM_PHASE_THRESHOLD,
)
from scraper.tiz import compute_tiz_causal, adaptive_calibration as _tiz_cal
from scraper.wave_resonance import compute_wave_resonance
from scraper.maps import _oc_coherence

# ── Basket definitions (V4 two-layer structural/vectorial architecture) ───────
BASKET_OC = {'nupl', 'mvrv_z_score', 'rhodl_ratio', 'cvdd_ratio', 'puell', 'lth_supply'}
BASKET_MS = {'cipherb', 'mayer_multiple', 'funding_rate', 'fear_greed', 'etf_flows'}
BASKET_MC = {'m2_yoy', 'yield_curve_spread'}
BASKET_CP = {'btc_price_cycle', 'pi_gap'}
BASKET_MIN_COUNTS = {'OC': 4, 'MS': 3, 'MC': 1, 'CP': 1}

# Legacy aliases (backward-compat for any external callers)
OC_GROUP   = BASKET_OC
TECH_GROUP = BASKET_MS | BASKET_MC | BASKET_CP

_CAL_PATH  = 'data/v3_calibration.json'
_cal_cache: dict | None = None
_hmm_cache: dict = {}   # keyed by model path; avoids re-loading pkl on every call


def load_calibration() -> dict:
    """Load scoring constants from data/v3_calibration.json."""
    global _cal_cache
    if _cal_cache is not None:
        return _cal_cache
    if os.path.exists(_CAL_PATH):
        try:
            with open(_CAL_PATH, encoding='utf-8') as f:
                _cal_cache = json.load(f)
                return _cal_cache
        except Exception:
            pass
    raise RuntimeError(
        f'{_CAL_PATH} missing. Run tools/calibrate_v3.py to generate it.'
    )


# ── Normalization ─────────────────────────────────────────────────────────────

_KEY_MAP = {
    'nupl':          'nupl',
    'mvrv':          'mvrv_z_score',
    'rhodl_ratio':   'rhodl_ratio',
    'cvdd_ratio':    'cvdd_ratio',
    'asopr':         'asopr',
    'puell_multiple':'puell',
    'mayer_multiple':'mayer_multiple',
    'fear_greed':    'fear_greed',
    'm2_mom':        'm2_yoy',
    'yield_curve':   'yield_curve_spread',
    'etf_flows':     'etf_flows',
    'funding_rate':  'funding_rate',
    'dxy':           'dxy',
    'lth_supply_pct':'lth_supply',
}


def _extract_pi_gap(v):
    if v is None:
        return None
    while isinstance(v, dict):
        if 'gap_pct' in v:
            return v['gap_pct']
        v = v.get('value')
    return float(v) if isinstance(v, (int, float)) else None


def _map_pi_gap(v) -> int | None:
    gap = _extract_pi_gap(v)
    if gap is None:
        return None
    gap = float(gap)
    if gap <= 0.0:
        return 100  # pi cross confirmed
    if gap > 20.0:
        return None  # indicator not firing — exclude from flat_avg entirely
    # gap 0..20%: linear 100..50
    return round(50 + (1.0 - gap / 20.0) * 50)


def _extract_cipherb(cb) -> tuple[int | None, int | None, int | None]:
    """Return (weekly_raw, daily_raw, blended_score) from cipherb metric."""
    if not isinstance(cb, dict):
        return None, None, None
    val_dict = cb.get('value', cb)
    if not isinstance(val_dict, dict):
        return None, None, None
    w = val_dict.get('weekly_score')
    d = val_dict.get('daily_score')
    weekly_raw = round(w) if w is not None else None
    daily_raw  = round(d) if d is not None else None
    if w is None:
        return weekly_raw, daily_raw, None
    if val_dict.get('fast_bearish_div'):
        w = min(100.0, w + 12)
    elif val_dict.get('fast_bullish_div'):
        w = max(0.0, w - 12)
    if d is not None:
        if val_dict.get('daily_fast_bearish_div'):
            d = min(100.0, d + 12)
        elif val_dict.get('daily_fast_bullish_div'):
            d = max(0.0, d - 12)
        blended = round(0.8 * w + 0.2 * d)
    else:
        blended = round(w)
    return weekly_raw, daily_raw, blended


def _normalize(raw_metrics: dict, target_date: datetime.date) -> dict:
    """Normalize all raw metrics to [0, 100] risk scores."""
    normalized: dict[str, int | None] = {}
    for raw_k, norm_k in _KEY_MAP.items():
        val = raw_metrics.get(raw_k)
        normalized[norm_k] = normalize_metric(norm_k, val, target_date)

    # Pi Cycle Gap
    pi_raw = (raw_metrics.get('pi_cycle')
              or raw_metrics.get('pi_cycle_gap_pct')
              or raw_metrics.get('pi_gap'))
    normalized['pi_gap'] = _map_pi_gap(pi_raw)

    # CipherB (weekly + daily blend, divergence-adjusted)
    cb = raw_metrics.get('cipherb')
    weekly_raw, daily_raw, blended = _extract_cipherb(cb)
    normalized['cipherb']         = blended
    normalized['cipherb_weekly']  = weekly_raw
    normalized['cipherb_daily']   = daily_raw

    # BTC price within current cycle (0=cycle bottom, 100=new cycle ATH)
    # Price comes from raw_metrics if available, otherwise caller must inject it separately.
    _price = raw_metrics.get('btc_price') or raw_metrics.get('price')
    normalized['btc_price_cycle'] = price_cycle_percentile(target_date, _price)

    return normalized


# ── Phase weights ─────────────────────────────────────────────────────────────

def _phase_weights(normalized: dict, prev_scores: dict | None) -> tuple[float, float, float, str, int, int]:
    """
    Compute continuous phase weights (w_bot, w_neutral, w_top) summing to 1.

    w_bot: bottom_confluence.py — calibrated from CONFIRMED_BOTTOM_DATES.
    w_top: HMM-like similarity weight. It is not a calibrated probability.
           Falls back to 0.0 when model unavailable (safe: neutral wins).

    Returns (w_bot, w_neutral, w_top, phase_label, top_signal, bot_signal).
    """
    w_top, w_bot, w_neutral = 0.0, 0.0, 1.0
    top_signal, bot_signal  = 0, 0
    phase = 'NEUTRAL'

    # ── w_bot: data-driven bottom confluence ──────────────────────────────────
    try:
        confluence = compute_bottom_confluence(normalized, _load_bc_cal())
        if confluence is not None:
            w_bot      = confluence / 100.0
            bot_signal = confluence
    except Exception:
        pass

    # ── w_top: heuristic HMM similarity weight (not probability-calibrated) ──
    try:
        import os, pickle
        model_path = 'data/v3_phase_model.pkl'
        if os.path.exists(model_path):
            if model_path not in _hmm_cache:
                try:
                    from tools.train_v3_hmm_model import HMMPhaseClassifier as _hmm_cls
                except ImportError:
                    _hmm_cls = None

                class _Unpickler(pickle.Unpickler):
                    def find_class(self, module, name):
                        if name == 'HMMPhaseClassifier' and _hmm_cls is not None:
                            return _hmm_cls
                        return super().find_class(module, name)

                with open(model_path, 'rb') as f:
                    _hmm_cache[model_path] = _Unpickler(f).load()['pipeline']

            pipeline = _hmm_cache[model_path]

            METRIC_ORDER = [
                'nupl', 'mvrv_z_score', 'rhodl_ratio', 'cvdd_ratio', 'mayer_multiple',
                'asopr', 'etf_flows', 'cipherb_weekly', 'cipherb_daily', 'fear_greed', 'm2_yoy',
            ]
            import numpy as np
            vec = []
            for m in METRIC_ORDER:
                vec.append(normalized.get(m))
            for m in METRIC_ORDER:
                s_now  = normalized.get(m)
                s_prev = (prev_scores or {}).get(m)
                vec.append(s_now - s_prev if (s_now is not None and s_prev is not None) else None)
            row   = [v if v is not None else float('nan') for v in vec]
            probs = pipeline.predict_proba(np.array([row], dtype=float))[0]
            w_top      = float(probs[2])  # only use top probability from HMM
            top_signal = round(w_top * 100)
    except Exception:
        pass

    # ── Consensus fallback when HMM unavailable (w_top still 0.0) ────────────
    # Uses the three best top/bottom discriminating metrics (disc power from
    # confirmed cycle extremes: cipherb +80.9, nupl +45.8, mvrv +44.6).
    # Phase score ≥62 → TOP; continuous w_top scaled 0.65→1.0 above threshold.
    if w_top == 0.0:
        _cb = normalized.get('cipherb')
        _nu = normalized.get('nupl')
        _mv = normalized.get('mvrv_z_score')
        _vals = [v for v in [_cb, _nu, _mv] if v is not None]
        if _vals:
            _ps = sum(_vals) / len(_vals)
            if _ps >= 62:
                w_top      = min(1.0, 0.65 + (_ps - 62) / 38.0 * 0.35)
                top_signal = round(w_top * 100)

    # ── Normalise so w_bot + w_top + w_neutral = 1 ───────────────────────────
    total = w_bot + w_top
    if total > 1.0:
        w_bot  /= total
        w_top  /= total
        w_neutral = 0.0
    else:
        w_neutral = max(0.0, 1.0 - total)

    # Phase label (informational only — no scoring logic gates on this string)
    if w_top > 0.40 and w_top > w_bot:
        phase = 'TOP'
    elif w_bot >= BOTTOM_PHASE_THRESHOLD and w_bot > w_top:
        phase = 'BOTTOM'

    return w_bot, w_neutral, w_top, phase, top_signal, bot_signal


# ── Weighted average helper ───────────────────────────────────────────────────

def _wavg(group_keys: set, normalized: dict, utilities: dict, min_count: int = 1) -> int | None:
    total_uw = total_us = 0.0
    active = 0
    for k in group_keys:
        s = normalized.get(k)
        u = utilities.get(k, 0.5)
        if s is not None:
            active += 1
            total_us += s * u
            total_uw += u
    return round(total_us / total_uw) if total_uw > 0 and active >= min_count else None


def assess_data_quality(normalized: dict) -> dict:
    """Classify whether basket coverage is sufficient for an actionable signal."""
    groups = {'OC': BASKET_OC, 'MS': BASKET_MS, 'MC': BASKET_MC, 'CP': BASKET_CP}
    counts = {name: sum(normalized.get(k) is not None for k in keys)
              for name, keys in groups.items()}
    coverage = {
        name: {'active': counts[name], 'total': len(keys), 'minimum': BASKET_MIN_COUNTS[name]}
        for name, keys in groups.items()
    }
    if all(counts[name] >= BASKET_MIN_COUNTS[name] for name in groups):
        status = 'valid'
    elif counts['OC'] >= 3 and counts['MS'] >= 2 and sum(counts.values()) >= 8:
        status = 'degraded'
    else:
        status = 'invalid'
    return {'status': status, 'baskets': coverage}


# ── Main scoring function ─────────────────────────────────────────────────────

def compute_score(
    raw_metrics: dict,
    target_date: datetime.date | str | None = None,
    prev_scores: dict | None = None,
    scores_history: list | None = None,
    btc_price: float | None = None,
) -> dict:
    """
    Compute the composite risk score for a given set of raw metric values.

    Parameters
    ----------
    raw_metrics    : dict  — raw values from live scraper or backtest reconstruction.
    target_date    : date  — used for causal normalization; defaults to today.
    prev_scores    : dict  — metric scores from N days ago (for top signal via Mahalanobis).
    scores_history : list  — [(date_str, score, phase?, w_bot?), ...] for TiZ.
    btc_price      : float — BTC price at target_date (passed through to signal).

    Returns
    -------
    dict with: final_score, phase, w_bot/w_neutral/w_top, tiz_*, oc_coherence,
               coh_factor, utilities, normalized_scores, wave_resonance, onchain_avg,
               tech_avg, top_signal, bot_signal, pi_cross, dxy_adj.
    """
    if isinstance(target_date, str):
        target_date = datetime.date.fromisoformat(target_date)
    elif target_date is None:
        target_date = datetime.date.today()

    cal = load_calibration()
    cd  = cal['coherence_dampening']
    tiz_cfg = cal['tiz']
    dxy_cfg = cal['dxy_modifier']

    # ── 1. Normalize ──────────────────────────────────────────────────────────
    # Inject btc_price so _normalize can compute btc_price_cycle
    _raw_with_price = dict(raw_metrics)
    if btc_price is not None and 'btc_price' not in _raw_with_price:
        _raw_with_price['btc_price'] = btc_price
    normalized = _normalize(_raw_with_price, target_date)

    # ── 2. Phase weights ──────────────────────────────────────────────────────
    if prev_scores is None:
        try:
            from scraper.scoring_v2 import _METRIC_LOOKBACK
            from scraper.wave_history import build_prev_scores_for_wave
            prev_scores = build_prev_scores_for_wave(target_date, _METRIC_LOOKBACK)
        except Exception:
            pass

    w_bot, w_neutral, w_top, phase, top_signal, bot_signal = _phase_weights(normalized, prev_scores)

    # Blend HMM phase weights with halving-cycle position prior (dynamic alpha)
    w_bot, w_neutral, w_top = blend_phase_with_cycle_prior(w_bot, w_neutral, w_top, target_date)

    # Update phase label to reflect blended weights
    if w_top >= 0.40 and w_top > w_bot:
        phase = 'TOP'
    elif w_bot >= BOTTOM_PHASE_THRESHOLD and w_bot > w_top:
        phase = 'BOTTOM'
    else:
        phase = 'NEUTRAL'

    # ── 3. Wave Resonance (independent — no V2 required) ─────────────────────
    pi_raw = (raw_metrics.get('pi_cycle')
              or raw_metrics.get('pi_cycle_gap_pct')
              or raw_metrics.get('pi_gap'))
    pi_gap_pct = _extract_pi_gap(pi_raw)

    def _scalar(v):
        """Extract numeric value from either a raw number or a {value: ...} dict."""
        if isinstance(v, dict):
            v = v.get('value')
        return float(v) if isinstance(v, (int, float)) else None

    nupl_raw = _scalar(raw_metrics.get('nupl'))
    wr_overrides = {
        'nupl':           nupl_raw,  # scores.json stores nupl in % — same units as window
        'mvrv':           _scalar(raw_metrics.get('mvrv')),
        'puell':          _scalar(raw_metrics.get('puell_multiple')),
        'cvdd_ratio':     _scalar(raw_metrics.get('cvdd_ratio')),
        'mayer_multiple': _scalar(raw_metrics.get('mayer_multiple')),
        'pi_gap_pct':     pi_gap_pct,
    }
    wr_overrides = {k: v for k, v in wr_overrides.items() if v is not None}
    wr = compute_wave_resonance(
        date=target_date.isoformat(),
        raw_overrides=wr_overrides if wr_overrides else None,
    )

    # ── 4. TiZ — continuous, no phase gate ───────────────────────────────────
    if scores_history is None:
        scores_path = 'data/history/scores.json'
        if os.path.exists(scores_path):
            try:
                with open(scores_path, encoding='utf-8') as f:
                    history_data = json.load(f)
                scores_history = [
                    (r['date'], r.get('final_score'), r.get('phase'), r.get('w_bot'))
                    for r in history_data if r.get('date')
                ]
            except Exception:
                pass

    tiz_score, tiz_days, tiz_calibration = compute_tiz_causal(
        scores_history, target_date
    )
    tiz_maturity = round(tiz_days / tiz_calibration, 3) if tiz_days > 0 else None

    # ── 5. Utility weights ────────────────────────────────────────────────────
    utilities = evaluate_all_utilities_continuous(
        normalized, w_top, w_bot, w_neutral, tiz_maturity
    )

    # ── 6a. Basket averages (V4) ──────────────────────────────────────────────
    quality = assess_data_quality(normalized)
    OC = _wavg(BASKET_OC, normalized, utilities, BASKET_MIN_COUNTS['OC'])
    MS = _wavg(BASKET_MS, normalized, utilities, BASKET_MIN_COUNTS['MS'])
    MC = _wavg(BASKET_MC, normalized, utilities, BASKET_MIN_COUNTS['MC'])
    CP = _wavg(BASKET_CP, normalized, utilities, BASKET_MIN_COUNTS['CP'])

    # Informational sub-scores (backward-compat keys for pipeline/dashboard)
    oc_avg   = OC
    tech_avg = _wavg(BASKET_MS | BASKET_MC | BASKET_CP, normalized, utilities, 5)

    # ── 6b. Step 1: CP contextualises OC (regime multiplier) ─────────────────
    CP_safe = CP if CP is not None else 50
    OC_read = OC * (0.60 + 0.40 * CP_safe / 100) if OC is not None else None

    # ── 6c. Step 2: F_structural ("where we are") ────────────────────────────
    w_mc = w_bot * 0.05 + w_neutral * 0.25 + w_top * 0.05
    if OC_read is not None:
        if MC is not None:
            F_structural = (1.0 - w_mc) * OC_read + w_mc * MC
        else:
            F_structural = OC_read
    elif MC is not None:
        F_structural = float(MC)
    else:
        F_structural = 50.0

    # TiZ blend: scales with w_bot (BOTTOM phase emphasis)
    if tiz_score is not None:
        tw = tiz_cfg['weight']  # 0.20
        F_structural = (1.0 - tw * w_bot) * F_structural + tw * w_bot * tiz_score

    # OC floor: prevent CP from over-discounting on-chain signal early in cycle
    if OC is not None:
        F_structural = max(F_structural, 0.70 * OC)

    # ── 6d. Coherence dampening — applied to F_structural only ───────────────
    oc_coherence = _oc_coherence(normalized)
    coh_factor   = 1.0
    coh_floor = (
        cd['bottom_coh_floor'] * w_bot
        + cd['neutral_coh_floor'] * w_neutral
        + cd['top_coh_floor']    * w_top
    )
    neutral_s = (
        cd['bottom_neutral_target'] * w_bot
        + cd['neutral_neutral_target'] * w_neutral
        + cd['top_neutral_target']    * w_top
    )
    coh_factor   = round(coh_floor + (1.0 - coh_floor) * oc_coherence, 3)
    F_structural = neutral_s + (F_structural - neutral_s) * coh_factor

    # ── 6e. Step 3: F_vectorial ("where we're going") ────────────────────────
    # div uses raw OC (not OC_read) to avoid phantom divergence when OC == CP
    div   = max(0, CP_safe - OC) if OC is not None else 0
    w_ms  = w_bot * 0.30 + w_neutral * 0.60 + w_top * 0.80
    w_div = w_top * 0.40
    denom = w_ms + w_div
    if MS is not None and denom > 0:
        F_vectorial = (w_ms * MS + w_div * div) / denom
    elif MS is not None:
        F_vectorial = float(MS)
    else:
        F_vectorial = float(div) if div > 0 else 50.0

    # ── 6f. Step 4: Headroom synthesis ───────────────────────────────────────
    phase_blend = w_bot * 0.20 + w_neutral * 0.50 + w_top * 1.00
    headroom    = 100.0 - F_structural
    final_float = F_structural + headroom * (F_vectorial / 100.0) * phase_blend

    # ── 6g. DXY macro modifier ────────────────────────────────────────────────
    dxy_score = normalized.get('dxy')
    dxy_adj   = 0.0
    if dxy_score is not None:
        if dxy_score > dxy_cfg['high']:
            dxy_adj = -min(dxy_cfg['max_adj'], (dxy_score - dxy_cfg['high']) * dxy_cfg['scale'])
        elif dxy_score < dxy_cfg['low']:
            dxy_adj = min(dxy_cfg['max_adj'], (dxy_cfg['low'] - dxy_score) * dxy_cfg['scale'])
        final_float += dxy_adj

    final = max(0, min(100, round(final_float)))

    # ── 6h. Pi Cycle top override ─────────────────────────────────────────────
    # pi_raw is a dict with 'cross' key during live scoring, but a plain float
    # (pi_gap_pct) during recompute from scores.json — detect both forms.
    _pi_gap_val = _extract_pi_gap(pi_raw)
    pi_cross = (
        (isinstance(pi_raw, dict) and bool(pi_raw.get('cross')))
        or (_pi_gap_val is not None and _pi_gap_val <= 0)
    )
    if pi_cross and final is not None:
        final = max(final, 85)

    # ── Raw-metric vector for Forward Risk ──────────────────────────────────
    def _s(v):
        if isinstance(v, dict): v = v.get('value')
        if isinstance(v, dict): v = v.get('value')
        return float(v) if isinstance(v, (int, float)) else None

    _cb = raw_metrics.get('cipherb')
    _cb_daily = None
    if isinstance(_cb, dict):
        _cb_inner = _cb.get('value', _cb)
        if isinstance(_cb_inner, dict):
            _cb_daily = _cb_inner.get('daily_score')

    _fr = raw_metrics.get('funding_rate')
    _fr_val = (_fr.get('value') or {}).get('avg_7d') if isinstance(_fr, dict) else None

    _lth_v = _s(raw_metrics.get('lth_supply_pct'))
    _lth_pct = (_lth_v / 21_000_000 * 100) if _lth_v is not None and _lth_v > 100 else _lth_v

    _mix_raw = {
        'btc_price':      _s(raw_metrics.get('btc_price')),
        'nupl':           _s(raw_metrics.get('nupl')),
        'mvrv':           _s(raw_metrics.get('mvrv')),
        'rhodl_ratio':    _s(raw_metrics.get('rhodl_ratio')),
        'cvdd_ratio':     _s(raw_metrics.get('cvdd_ratio')),
        'puell':          _s(raw_metrics.get('puell_multiple')),
        'cipherb_daily':  _cb_daily,
        'mayer_multiple': _s(raw_metrics.get('mayer_multiple')),
        'fear_greed':     _s(raw_metrics.get('fear_greed')),
        'funding_rate':   _fr_val,
        'm2_yoy':         _s(raw_metrics.get('m2_mom')),
        'lth_supply_pct': _lth_pct,
        'yield_curve':    _s(raw_metrics.get('yield_curve')),
        'dxy':            _s(raw_metrics.get('dxy')),
    }

    # ── Forward Risk (diagnostic prediction layer) ───────────────────────────
    # Predicts expected max drawdown over the next 365 days. Its inputs include
    # V3 context, so it is a distinct target rather than an independent signal.
    v5b_score: float | None = None
    v5b_validated = False
    try:
        from scraper import mixing_model_b as _v5b
        _v5b_result = _v5b.predict_b(
            _mix_raw,
            target_date=target_date,
            w_top=round(w_top, 3),
            w_bot=round(w_bot, 3),
            v3_score=float(final),
        )
        if isinstance(_v5b_result, dict):
            v5b_score = _v5b_result['score']
            v5b_validated = bool(_v5b_result.get('validated'))
    except Exception as e:
        print(f'Warning: V5B (v5b_score / Outlook) failed — {e}')

    # ── Market Regime — decision layer (Outlook + Market Context) ───────────
    # Thresholds derived from 2018-2026 backtest (163x return vs 4.8x B&H).
    # Mirrors scraper/scoring_v3.py::_market_regime() — see docs/architecture.md
    # §7.2 for the full rationale and the Wait-vs-Hold distinction.
    market_regime:    str | None = None
    composite_risk:   float | None = None
    signal_agreement: float | None = None
    meta_score:       float | None = None
    decision_suppressed = quality['status'] != 'valid' or not v5b_validated
    suppression_reasons = []
    if quality['status'] != 'valid':
        suppression_reasons.append(f"data_quality_{quality['status']}")
    if not v5b_validated:
        suppression_reasons.append('v5b_not_better_than_baseline')
    if v5b_score is not None and final is not None:
        _mc = float(final)
        buy  = _mc <  35 and v5b_score <  20
        sell = _mc >= 65 and v5b_score >= 45
        hold = _mc >= 65 and v5b_score <  45
        market_regime = 'Buy' if buy else 'Sell' if sell else 'Hold' if hold else 'Wait'
        if decision_suppressed:
            market_regime = 'Unavailable' if quality['status'] == 'invalid' else 'Wait'
        # Composite risk = √(Market Context × Outlook) — display gauge only, not used in market_regime.
        composite_risk   = round(math.sqrt(max(0.0, _mc) * max(0.0, v5b_score)), 1)
        signal_agreement = round(1.0 - abs(_mc - v5b_score) / 100.0, 2)
        _w_mc  = signal_agreement / 2
        _w_v5b = 1.0 - _w_mc
        meta_score = round(_w_mc * _mc + _w_v5b * v5b_score, 1)

    return {
        'final_score':        final,
        'phase':              phase,
        'w_bot':              round(w_bot, 3),
        'w_neutral':          round(w_neutral, 3),
        'w_top':              round(w_top, 3),
        'phase_method':       'heuristic_hmm_cycle_blend',
        'phase_probabilistic': False,
        'top_signal':         top_signal,
        'bot_signal':         bot_signal,
        'onchain_avg':        oc_avg,
        'tech_avg':           tech_avg,
        'oc_basket':          round(OC) if OC is not None else None,
        'ms_basket':          round(MS) if MS is not None else None,
        'mc_basket':          round(MC) if MC is not None else None,
        'cp_basket':          round(CP) if CP is not None else None,
        'oc_read':            round(OC_read) if OC_read is not None else None,
        'tiz_score':          tiz_score,
        'tiz_days':           tiz_days,
        'tiz_maturity':       tiz_maturity,
        'tiz_calibration':    tiz_calibration,
        'oc_coherence':       round(oc_coherence, 3),
        'coh_factor':         coh_factor,
        'pi_cross':           pi_cross,
        'dxy_adj':            round(dxy_adj, 2),
        'wave_resonance':     wr,
        'utilities':          utilities,
        'v5b_score':          v5b_score,
        'v5b_validated':      v5b_validated,
        'market_regime':      market_regime,
        'score_status':       quality['status'],
        'basket_coverage':    quality['baskets'],
        'decision_suppressed': decision_suppressed,
        'decision_suppression_reason': ','.join(suppression_reasons) or None,
        'composite_risk':     composite_risk,
        'signal_agreement':   signal_agreement,
        'meta_score':         meta_score,
        'normalized_scores':  {
            k: round(v) for k, v in normalized.items()
            if v is not None and k not in ('cipherb_weekly', 'cipherb_daily')
        },
    }
